version: '3.8'

services:
  chatbot:
    build: ./chatbot
    environment:
    - APY_KEY_=${APY_KEY_}
    - LOG_LEVEL=debug

  llm:
    build: ./llm
    ports:
    - "5005:5005"
    environment:
    - OPENAI_API_KEY=${OPENAI_API_KEY}
    - LOG_LEVEL=debug